export const ASSETS = {
  BASE_URLS: {
    PICSUM: '',
    YOUTUBE_WATCH: 'https://youtu.be',
    YOUTUBE_WATCH_WWW: 'https://www.youtube.com/watch',
  },
  IMAGES: {
    PLACEHOLDER_SQUARE: '',
    PLACEHOLDER_PORTRAIT: '',
    PLACEHOLDER_LANDSCAPE: '',
    AVATAR_DOG: '',
    THUMBNAILS: {
      MINECRAFT: '',
      BLAZES: '',
      ESCAPES: '',
      FUN: '',
      JOYRIDE: '',
      SINTEL: '',
      KAI: '',
      GAMEPLAY: '',
      SUBWAY: '',
      CAT: '',
      DOG_SMALL: '',
      STAIRS_1: '',
      STAIRS_2: '',
      STAIRS_3: '',
      WOLF: '',
      CHAT: '',
      GTA: '',
      AI_ART: '',
      LOGO: '',
    },
    UNSPLASH: {
      VERTICAL_1: '',
      VERTICAL_2: '',
      FIRE: '',
      LAVA: '',
      SPACE: '',
      NATURE: '',
      TEXTURE: '',
    },
  },
  VIDEOS: {
    MELTDOWNS: '',
    BLAZES: '',
    ESCAPES: '',
    FUN: '',
    JOYRIDES: '',
    SINTEL: '',
    SAMPLE_1: '',
    SAMPLE_2: '',
  },
  PLACEHOLDERS: {
    AUDIO_URL_1: '',
    AUDIO_URL_2: '',
  },
  AUDIO: {
    SOUNDHELIX_BASE: '',
    TRACKS: {
      SITTING: '',
      ANTICIPATION: '',
      REGGAE: '',
      HIPHOP: '',
      SHOWDOWN: '',
      SPRING: '',
    },
  },
  SOCIAL: {
    DISCORD: '',
  },
};