export const DESIGN_TOKENS = {
  container: {
    maxWidth: '1200px',
    padding: {
      mobile: '16px',
      tablet: '24px',
      desktop: '24px',
    },
  },
  layout: {
    sidebar: {
      width: '104px',
      offset: '116px',
    },
    content: {
      base: '1400px',
      wide: '1600px',
    },
  },
  grid: {
    columns: 12,
    gutter: '24px',
    container: '1200px',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    '2xl': '48px',
    '3xl': '64px',
  },
  typography: {
    fontFamily: {
      primary: 'Inter, system-ui, sans-serif',
      secondary: 'Montserrat, system-ui, sans-serif',
      display: 'Sora, system-ui, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    fontSize: {
      xs: '12px',
      sm: '14px',
      base: '16px',
      lg: '18px',
      xl: '20px',
      '2xl': '24px',
      '3xl': '32px',
      '4xl': '48px',
    },
    fontWeight: {
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
    },
    lineHeight: {
      tight: '1.25',
      normal: '1.5',
      relaxed: '1.75',
    },
  },
  card: {
    borderRadius: {
      sm: '8px',
      md: '12px',
      lg: '16px',
      xl: '24px',
    },
    padding: {
      outer: '24px',
      inner: '16px',
    },
    minHeight: {
      feature: '320px',
      action: '280px',
      compact: '240px',
    },
    shadow: {
      default: '0 4px 12px rgba(0, 0, 0, 0.08)',
      hover: '0 8px 24px rgba(0, 0, 0, 0.12)',
      active: '0 2px 8px rgba(0, 0, 0, 0.06)',
    },
  },
  colors: {
    background: {
      primary: '#0a0b1e',
      secondary: '#0a0a0a',
      surface: '#1a1a1a',
      overlay: 'rgba(0, 0, 0, 0.8)',
    },
    text: {
      primary: '#ffffff',
      secondary: '#a3a3a3',
      tertiary: '#737373',
      accent: '#3b82f6',
    },
    border: {
      default: 'rgba(255, 255, 255, 0.08)',
      hover: 'rgba(255, 255, 255, 0.15)',
      focus: 'rgba(59, 130, 246, 0.5)',
    },
    brand: {
      primary: '#3b82f6',
      secondary: '#8b5cf6',
      accent: '#f59e0b',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      orange: '#fb923c',
      pink: '#ec4899',
    },
    social: {
      instagram: {
        primary: '#E4405F',
        gradient: ['#833AB4', '#E4405F', '#FCAF45'],
      },
      tiktok: '#000000',
      youtube: '#FF0000',
    },
    editor: {
      canvas: {
        defaultBg: '#3b82f6',
        guide: '#f97316',
      },
      text: {
        default: '#ffffff',
        stroke: '#000000',
        bg: 'transparent',
      },
      subtitle: {
        templates: {
          white: '#ffffff',
          black: '#000000',
          yellow: '#ffff00',
          green: '#00ff00',
          purple: '#9333ea',
          pink: '#ff69b4',
          coral: '#ff6b6b',
          red: '#ff0000',
        },
      },
    },
    canvas: '#000000',
    ranking: {
      bg: '#2b2a2a',
      text: '#ffffff',
      stroke: '#000000',
    },
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
  animation: {
    duration: {
      fast: '150ms',
      normal: '250ms',
      slow: '350ms',
    },
    easing: {
      ease: 'ease',
      'ease-in': 'ease-in',
      'ease-out': 'ease-out',
      'ease-in-out': 'ease-in-out',
    },
  },
  zIndex: {
    base: 0,
    dropdown: 1000,
    sticky: 1020,
    fixed: 1030,
    modal: 1040,
    popover: 1050,
    tooltip: 1060,
    overlay: 1070,
  },
  borderRadius: {
    none: '0',
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '16px',
    '2xl': '24px',
    full: '9999px',
  },
  shadow: {
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
    xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
  },
} as const;
export const getSpacing = (size: keyof typeof DESIGN_TOKENS.spacing) => DESIGN_TOKENS.spacing[size];
export const getFontSize = (size: keyof typeof DESIGN_TOKENS.typography.fontSize) => DESIGN_TOKENS.typography.fontSize[size];
export const getFontWeight = (weight: keyof typeof DESIGN_TOKENS.typography.fontWeight) => DESIGN_TOKENS.typography.fontWeight[weight];
export const getBorderRadius = (size: keyof typeof DESIGN_TOKENS.card.borderRadius) => DESIGN_TOKENS.card.borderRadius[size];
export const getShadow = (size: keyof typeof DESIGN_TOKENS.shadow) => DESIGN_TOKENS.shadow[size];
export const CSS_CUSTOM_PROPERTIES = {
  '--color-background-primary': DESIGN_TOKENS.colors.background.primary,
  '--color-background-secondary': DESIGN_TOKENS.colors.background.secondary,
  '--color-background-surface': DESIGN_TOKENS.colors.background.surface,
  '--color-text-primary': DESIGN_TOKENS.colors.text.primary,
  '--color-text-secondary': DESIGN_TOKENS.colors.text.secondary,
  '--color-text-accent': DESIGN_TOKENS.colors.text.accent,
  '--color-border-default': DESIGN_TOKENS.colors.border.default,
  '--color-brand-primary': DESIGN_TOKENS.colors.brand.primary,
  '--color-brand-secondary': DESIGN_TOKENS.colors.brand.secondary,
  '--color-brand-accent': DESIGN_TOKENS.colors.brand.accent,
  '--color-brand-orange': DESIGN_TOKENS.colors.brand.orange,
  '--color-brand-pink': DESIGN_TOKENS.colors.brand.pink,
  '--color-social-instagram-primary': DESIGN_TOKENS.colors.social.instagram.primary,
  '--color-social-tiktok': DESIGN_TOKENS.colors.social.tiktok,
  '--color-social-youtube': DESIGN_TOKENS.colors.social.youtube,
  '--color-editor-canvas-default-bg': DESIGN_TOKENS.colors.editor.canvas.defaultBg,
  '--color-editor-canvas-guide': DESIGN_TOKENS.colors.editor.canvas.guide,
  '--color-editor-text-default': DESIGN_TOKENS.colors.editor.text.default,
  '--color-editor-text-stroke': DESIGN_TOKENS.colors.editor.text.stroke,
  '--color-canvas': DESIGN_TOKENS.colors.canvas,
  '--color-ranking-bg': DESIGN_TOKENS.colors.ranking.bg,
  '--color-ranking-text': DESIGN_TOKENS.colors.ranking.text,
  '--color-ranking-stroke': DESIGN_TOKENS.colors.ranking.stroke,
  '--spacing-xs': DESIGN_TOKENS.spacing.xs,
  '--spacing-sm': DESIGN_TOKENS.spacing.sm,
  '--spacing-md': DESIGN_TOKENS.spacing.md,
  '--spacing-lg': DESIGN_TOKENS.spacing.lg,
  '--spacing-xl': DESIGN_TOKENS.spacing.xl,
  '--spacing-2xl': DESIGN_TOKENS.spacing['2xl'],
  '--spacing-3xl': DESIGN_TOKENS.spacing['3xl'],
  '--border-radius-sm': DESIGN_TOKENS.borderRadius.sm,
  '--border-radius-md': DESIGN_TOKENS.card.borderRadius.md,
  '--border-radius-lg': DESIGN_TOKENS.card.borderRadius.lg,
  '--border-radius-xl': DESIGN_TOKENS.card.borderRadius.xl,
  '--border-radius-2xl': DESIGN_TOKENS.borderRadius['2xl'],
  '--border-radius-full': DESIGN_TOKENS.borderRadius.full,
  '--shadow-md': DESIGN_TOKENS.shadow.md,
  '--type-family-primary': DESIGN_TOKENS.typography.fontFamily.primary,
  '--type-family-secondary': DESIGN_TOKENS.typography.fontFamily.secondary,
  '--type-family-display': DESIGN_TOKENS.typography.fontFamily.display,
  '--type-family-mono': DESIGN_TOKENS.typography.fontFamily.mono,
  '--animation-duration-fast': DESIGN_TOKENS.animation.duration.fast,
  '--animation-duration-normal': DESIGN_TOKENS.animation.duration.normal,
  '--animation-duration-slow': DESIGN_TOKENS.animation.duration.slow,
  '--animation-easing-ease': DESIGN_TOKENS.animation.easing.ease,
  '--animation-easing-ease-in': DESIGN_TOKENS.animation.easing['ease-in'],
  '--animation-easing-ease-out': DESIGN_TOKENS.animation.easing['ease-out'],
  '--animation-easing-ease-in-out': DESIGN_TOKENS.animation.easing['ease-in-out'],
} as const;