export const IMAGE_GENERATION_DELAY_MS = 2500;
export const VOICE_GENERATION_INTERVAL_MS = 80;
export const VOICE_GENERATION_PROGRESS_STEP = 2;
export const RECORDING_INTERVAL_MS = 1000;
export const ANIMATION_STAGGER_DELAY_SECONDS = 0.1;
export const CHAT_MESSAGE_DELAY_SECONDS = 0.5;

export const GENERATION = {
  INTERVAL_MS: 100,
  FAST_INTERVAL_MS: 50,
  ANALYSIS_INTERVAL_MS: 80,
  PROGRESS_STEP: 2,
  ANALYSIS_PROGRESS_STEP: 3,
  MAX_PROGRESS: 100,
} as const;