import { VideoTemplate, Clip, Track } from '../types';
const DEFAULT_TRACKS: Track[] = [
  { id: 'video-1', type: 'video', label: 'Video 1', isMuted: false, isLocked: false, isHidden: false },
  { id: 'video-2', type: 'video', label: 'Video 2', isMuted: false, isLocked: false, isHidden: false },
  { id: 'audio-1', type: 'audio', label: 'Audio 1', isMuted: false, isLocked: false, isHidden: false },
  { id: 'audio-2', type: 'audio', label: 'Audio 2', isMuted: false, isLocked: false, isHidden: false },
];
const createDefaultClipProperties = () => ({
  scale: 100,
  positionX: 50,
  positionY: 50,
  rotation: 0,
  opacity: 100,
  volume: 100,
  speed: 1,
});
export const VIDEO_TEMPLATES: VideoTemplate[] = [
  {
    id: 'template-faceless-reddit',
    name: 'Reddit Story',
    description: 'Classic Reddit story format with gameplay background and TTS narration',
    thumbnail: 'https://picsum.photos/320/180?random=1',
    category: 'faceless',
    aspectRatio: '9:16',
    duration: 60,
    tracks: DEFAULT_TRACKS,
    clips: [
      {
        id: 'clip-bg-1',
        trackId: 'video-1',
        mediaId: 'gameplay-1',
        type: 'video',
        title: 'Gameplay Background',
        startTime: 0,
        duration: 60,
        inPoint: 0,
        outPoint: 60,
        properties: createDefaultClipProperties(),
        color: 'bg-blue-600',
      },
      {
        id: 'clip-text-1',
        trackId: 'video-2',
        mediaId: 'text-1',
        type: 'text',
        title: 'Story Title',
        startTime: 0,
        duration: 5,
        inPoint: 0,
        outPoint: 5,
        properties: {
          ...createDefaultClipProperties(),
          text: 'AITA for...',
          fontSize: 48,
          fontFamily: 'Montserrat',
          textColor: '#ffffff',
          positionY: 20,
        },
        color: 'bg-purple-600',
      },
      {
        id: 'clip-audio-1',
        trackId: 'audio-1',
        mediaId: 'tts-1',
        type: 'audio',
        title: 'TTS Narration',
        startTime: 0,
        duration: 55,
        inPoint: 0,
        outPoint: 55,
        properties: createDefaultClipProperties(),
        color: 'bg-green-600',
      },
      {
        id: 'clip-music-1',
        trackId: 'audio-2',
        mediaId: 'music-1',
        type: 'audio',
        title: 'Background Music',
        startTime: 0,
        duration: 60,
        inPoint: 0,
        outPoint: 60,
        properties: { ...createDefaultClipProperties(), volume: 30 },
        color: 'bg-amber-600',
      },
    ],
  },
  {
    id: 'template-faceless-quiz',
    name: 'Quiz/Trivia',
    description: 'Engaging quiz format with questions and reveal animations',
    thumbnail: 'https://picsum.photos/320/180?random=2',
    category: 'faceless',
    aspectRatio: '9:16',
    duration: 45,
    tracks: DEFAULT_TRACKS,
    clips: [
      {
        id: 'clip-bg-quiz',
        trackId: 'video-1',
        mediaId: 'abstract-bg',
        type: 'video',
        title: 'Abstract Background',
        startTime: 0,
        duration: 45,
        inPoint: 0,
        outPoint: 45,
        properties: createDefaultClipProperties(),
        color: 'bg-indigo-600',
      },
      {
        id: 'clip-question',
        trackId: 'video-2',
        mediaId: 'text-question',
        type: 'text',
        title: 'Question',
        startTime: 2,
        duration: 8,
        inPoint: 0,
        outPoint: 8,
        properties: {
          ...createDefaultClipProperties(),
          text: 'What is the capital of France?',
          fontSize: 36,
          fontFamily: 'Inter',
          textColor: '#ffffff',
          positionY: 30,
        },
        color: 'bg-cyan-600',
      },
    ],
  },
  {
    id: 'template-ranking',
    name: 'Top 10 Ranking',
    description: 'Countdown ranking video with dynamic transitions',
    thumbnail: 'https://picsum.photos/320/180?random=3',
    category: 'ranking',
    aspectRatio: '9:16',
    duration: 90,
    tracks: DEFAULT_TRACKS,
    clips: [
      {
        id: 'clip-ranking-bg',
        trackId: 'video-1',
        mediaId: 'gradient-bg',
        type: 'video',
        title: 'Gradient Background',
        startTime: 0,
        duration: 90,
        inPoint: 0,
        outPoint: 90,
        properties: createDefaultClipProperties(),
        color: 'bg-rose-600',
      },
      {
        id: 'clip-ranking-title',
        trackId: 'video-2',
        mediaId: 'text-title',
        type: 'text',
        title: 'Top 10 Title',
        startTime: 0,
        duration: 5,
        inPoint: 0,
        outPoint: 5,
        properties: {
          ...createDefaultClipProperties(),
          text: 'TOP 10',
          fontSize: 64,
          fontFamily: 'Bebas Neue',
          textColor: '#ffffff',
        },
        color: 'bg-orange-600',
      },
    ],
  },
  {
    id: 'template-tutorial',
    name: 'Tutorial/How-To',
    description: 'Step-by-step tutorial format with numbered sections',
    thumbnail: 'https://picsum.photos/320/180?random=4',
    category: 'tutorial',
    aspectRatio: '16:9',
    duration: 120,
    tracks: DEFAULT_TRACKS,
    clips: [
      {
        id: 'clip-tutorial-intro',
        trackId: 'video-1',
        mediaId: 'screen-recording',
        type: 'video',
        title: 'Screen Recording',
        startTime: 0,
        duration: 120,
        inPoint: 0,
        outPoint: 120,
        properties: createDefaultClipProperties(),
        color: 'bg-emerald-600',
      },
      {
        id: 'clip-tutorial-step',
        trackId: 'video-2',
        mediaId: 'text-step',
        type: 'text',
        title: 'Step 1',
        startTime: 5,
        duration: 10,
        inPoint: 0,
        outPoint: 10,
        properties: {
          ...createDefaultClipProperties(),
          text: 'Step 1: Getting Started',
          fontSize: 32,
          fontFamily: 'Inter',
          textColor: '#ffffff',
          positionY: 10,
        },
        color: 'bg-teal-600',
      },
    ],
  },
  {
    id: 'template-promo',
    name: 'Product Promo',
    description: 'Dynamic product showcase with call-to-action',
    thumbnail: 'https://picsum.photos/320/180?random=5',
    category: 'promo',
    aspectRatio: '1:1',
    duration: 30,
    tracks: DEFAULT_TRACKS,
    clips: [
      {
        id: 'clip-promo-bg',
        trackId: 'video-1',
        mediaId: 'product-shot',
        type: 'image',
        title: 'Product Shot',
        startTime: 0,
        duration: 30,
        inPoint: 0,
        outPoint: 30,
        properties: createDefaultClipProperties(),
        color: 'bg-violet-600',
      },
      {
        id: 'clip-promo-cta',
        trackId: 'video-2',
        mediaId: 'text-cta',
        type: 'text',
        title: 'CTA Text',
        startTime: 20,
        duration: 10,
        inPoint: 0,
        outPoint: 10,
        properties: {
          ...createDefaultClipProperties(),
          text: 'Shop Now →',
          fontSize: 28,
          fontFamily: 'Poppins',
          textColor: '#ffffff',
          positionY: 80,
        },
        color: 'bg-pink-600',
      },
    ],
  },
  {
    id: 'template-story-split',
    name: 'Split Screen Story',
    description: 'Two-panel layout for reactions or comparisons',
    thumbnail: 'https://picsum.photos/320/180?random=6',
    category: 'story',
    aspectRatio: '9:16',
    duration: 45,
    tracks: DEFAULT_TRACKS,
    clips: [
      {
        id: 'clip-split-top',
        trackId: 'video-1',
        mediaId: 'video-top',
        type: 'video',
        title: 'Top Video',
        startTime: 0,
        duration: 45,
        inPoint: 0,
        outPoint: 45,
        properties: {
          ...createDefaultClipProperties(),
          scale: 100,
          positionY: 25,
        },
        color: 'bg-sky-600',
      },
      {
        id: 'clip-split-bottom',
        trackId: 'video-2',
        mediaId: 'video-bottom',
        type: 'video',
        title: 'Bottom Video',
        startTime: 0,
        duration: 45,
        inPoint: 0,
        outPoint: 45,
        properties: {
          ...createDefaultClipProperties(),
          scale: 100,
          positionY: 75,
        },
        color: 'bg-lime-600',
      },
    ],
  },
];
export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'All Templates' },
  { id: 'faceless', label: 'Faceless' },
  { id: 'story', label: 'Story' },
  { id: 'ranking', label: 'Ranking' },
  { id: 'tutorial', label: 'Tutorial' },
  { id: 'promo', label: 'Promo' },
];