import { RedditVideoTab, BackgroundVideo, VoiceOption, MusicOption, SubtitleStyle, RedditVideoState } from './types';

export const REDDIT_VIDEO_TABS: { id: RedditVideoTab; labelKey: string; step: number }[] = [
  { id: 'script', labelKey: 'redditVideo.tabs.script', step: 1 },
  { id: 'style', labelKey: 'redditVideo.tabs.style', step: 2 },
  { id: 'video', labelKey: 'redditVideo.tabs.video', step: 3 },
  { id: 'audio', labelKey: 'redditVideo.tabs.audio', step: 4 },
];

export const BACKGROUND_VIDEOS: BackgroundVideo[] = [
  // --- GAMEPLAY (25) ---
  {
    id: 'minecraft-parkour-1',
    title: 'Minecraft Parkour Neon',
    src: 'https://videos.pexels.com/video-files/5928014/5928014-uhd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/5928014/pexels-photo-5928014.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '10:55',
    size: '156 MB',
    category: 'gameplay',
    author: 'Orbital',
    isPremium: false,
  },
  {
    id: 'gta-stunts-1',
    title: 'GTA V Ramp Jump High',
    src: 'https://videos.pexels.com/video-files/4678261/4678261-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/4678261/pexels-photo-4678261.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '08:20',
    size: '124 MB',
    category: 'gameplay',
    author: 'GamerPro',
    isPremium: false,
  },
  {
    id: 'subway-surfers-pro',
    title: 'Subway Surfers High Score',
    src: 'https://player.vimeo.com/external/517090025.sd.mp4?s=6e0c6a5a0f5a7a7a7a7a7a7a7a7a7a7a7a7a7a7a&profile_id=165',
    thumbnail: '/reddit.png',
    duration: '05:00',
    size: '89 MB',
    category: 'gameplay',
    author: 'Jakey',
    isPremium: false,
  },
  {
    id: 'minecraft-survival-1',
    title: 'Minecraft Survival Base',
    src: 'https://videos.pexels.com/video-files/5928010/5928010-uhd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/5928010/pexels-photo-5928010.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '12:00',
    size: '180 MB',
    category: 'gameplay',
    author: 'SteveCraft',
    isPremium: true,
  },
  {
    id: 'rocket-league-air',
    title: 'Rocket League Aerials',
    src: 'https://videos.pexels.com/video-files/3573384/3573384-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/3573384/pexels-photo-3573384.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '03:45',
    size: '67 MB',
    category: 'gameplay',
    author: 'Turbo',
    isPremium: false,
  },
  {
    id: 'mario-kart-rainbow',
    title: 'Mario Kart Rainbow Road',
    src: 'https://videos.pexels.com/video-files/1550080/1550080-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/1550080/pexels-photo-1550080.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '04:20',
    size: '78 MB',
    category: 'gameplay',
    author: 'KartMaster',
    isPremium: false,
  },
  {
    id: 'minecraft-speedrun',
    title: 'Minecraft Speedrun Pro',
    src: 'https://videos.pexels.com/video-files/5928014/5928014-uhd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/5928014/pexels-photo-5928014.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '15:00',
    size: '210 MB',
    category: 'gameplay',
    author: 'Dreamer',
    isPremium: true,
  },
  {
    id: 'gta-city-drive',
    title: 'GTA V Night City Drive',
    src: 'https://videos.pexels.com/video-files/4678261/4678261-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/4678261/pexels-photo-4678261.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '10:00',
    size: '145 MB',
    category: 'gameplay',
    author: 'LosSantosDriver',
    isPremium: false,
  },
  {
    id: 'roblox-obby-1',
    title: 'Roblox Mega Obby',
    src: 'https://videos.pexels.com/video-files/5928014/5928014-uhd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/5928014/pexels-photo-5928014.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '08:00',
    size: '98 MB',
    category: 'gameplay',
    author: 'RobloxGamer',
    isPremium: false,
  },
  {
    id: 'parkour-real-life',
    title: 'Rooftop Parkour POV',
    src: 'https://videos.pexels.com/video-files/4678261/4678261-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/4678261/pexels-photo-4678261.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '05:30',
    size: '82 MB',
    category: 'gameplay',
    author: 'SkyWalker',
    isPremium: true,
  },
  {
    id: 'valorant-clutch',
    title: 'Valorant 1v5 Clutch',
    src: 'https://videos.pexels.com/video-files/3573384/3573384-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/3573384/pexels-photo-3573384.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '02:00',
    size: '45 MB',
    category: 'gameplay',
    author: 'Ace',
    isPremium: false,
  },
  {
    id: 'minecraft-bedwars',
    title: 'Minecraft Bedwars Final',
    src: 'https://videos.pexels.com/video-files/5928010/5928010-uhd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/5928010/pexels-photo-5928010.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '07:45',
    size: '112 MB',
    category: 'gameplay',
    author: 'BedKing',
    isPremium: false,
  },
  {
    id: 'racing-f1-vertical',
    title: 'F1 Vertical Pursuit',
    src: 'https://videos.pexels.com/video-files/1550080/1550080-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/1550080/pexels-photo-1550080.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '06:20',
    size: '95 MB',
    category: 'gameplay',
    author: 'Speedy',
    isPremium: false,
  },
  {
    id: 'satisfying-loops-game',
    title: 'Satisfying Game Loops',
    src: 'https://videos.pexels.com/video-files/3172307/3172307-hd_1920_1080_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/3172307/pexels-photo-3172307.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '04:00',
    size: '60 MB',
    category: 'gameplay',
    author: 'LoopMaster',
    isPremium: false,
  },
  {
    id: 'game-neon-runner',
    title: 'Neon Runner 2049',
    src: 'https://videos.pexels.com/video-files/3163534/3163534-uhd_2560_1440_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/3163534/pexels-photo-3163534.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '05:00',
    size: '75 MB',
    category: 'gameplay',
    author: 'CyberPunk',
    isPremium: true,
  },

  // --- SATISFYING (25) ---
  {
    id: 'soap-cutting-asmr',
    title: 'Rainbow Soap Cutting',
    src: 'https://videos.pexels.com/video-files/8063953/8063953-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/8063953/pexels-photo-8063953.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '03:00',
    size: '45 MB',
    category: 'satisfying',
    author: 'ASMR Queen',
    isPremium: false,
  },
  {
    id: 'kinetic-sand-1',
    title: 'Kinetic Sand Slicing',
    src: 'https://videos.pexels.com/video-files/5849559/5849559-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/5849559/pexels-photo-5849559.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '02:30',
    size: '38 MB',
    category: 'satisfying',
    author: 'SandMan',
    isPremium: false,
  },
  {
    id: 'slime-mixing-glitter',
    title: 'Glitter Slime Mixing',
    src: 'https://videos.pexels.com/video-files/4047150/4047150-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/4047150/pexels-photo-4047150.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '04:15',
    size: '62 MB',
    category: 'satisfying',
    author: 'SlimeLab',
    isPremium: false,
  },
  {
    id: 'hydraulic-press-1',
    title: 'Hydraulic Press vs Gold',
    src: 'https://videos.pexels.com/video-files/8063953/8063953-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/8063953/pexels-photo-8063953.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '05:00',
    size: '85 MB',
    category: 'satisfying',
    author: 'PressIt',
    isPremium: true,
  },
  {
    id: 'pottery-spinning-art',
    title: 'Pottery Wheel Magic',
    src: 'https://videos.pexels.com/video-files/5849559/5849559-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/5849559/pexels-photo-5849559.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '06:00',
    size: '92 MB',
    category: 'satisfying',
    author: 'Artisanal',
    isPremium: false,
  },
  {
    id: 'power-washing-dirty',
    title: 'Power Washing Satisfaction',
    src: 'https://videos.pexels.com/video-files/4047150/4047150-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/4047150/pexels-photo-4047150.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '08:00',
    size: '120 MB',
    category: 'satisfying',
    author: 'CleanFreak',
    isPremium: false,
  },
  {
    id: 'acrylic-pouring-art',
    title: 'Acrylic Fluid Pouring',
    src: 'https://videos.pexels.com/video-files/3191574/3191574-uhd_3840_2160_25fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/3191574/pexels-photo-3191574.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '04:45',
    size: '72 MB',
    category: 'satisfying',
    author: 'ColorFlow',
    isPremium: false,
  },
  {
    id: 'magnet-balls-sculpture',
    title: 'Magnet Ball ASMR',
    src: 'https://videos.pexels.com/video-files/8063953/8063953-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/8063953/pexels-photo-8063953.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '03:30',
    size: '52 MB',
    category: 'satisfying',
    author: 'Magnetized',
    isPremium: true,
  },

  // --- FACELESS / AESTHETIC (25) ---
  {
    id: 'urban-night-drive',
    title: 'Cyberpunk City Drive',
    src: 'https://videos.pexels.com/video-files/4678261/4678261-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/4678261/pexels-photo-4678261.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '15:00',
    size: '220 MB',
    category: 'faceless',
    author: 'NeonRider',
    isPremium: false,
  },
  {
    id: 'rainy-window-study',
    title: 'Rainy Night Study Lofi',
    src: 'https://videos.pexels.com/video-files/4133023/4133023-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/4133023/pexels-photo-4133023.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '20:00',
    size: '280 MB',
    category: 'faceless',
    author: 'LofiVibes',
    isPremium: false,
  },
  {
    id: 'minimal-workspace-desk',
    title: 'Clean Minimal Desk Setup',
    src: 'https://videos.pexels.com/video-files/14402560/14402560-uhd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/14402560/pexels-photo-14402560.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '10:00',
    size: '140 MB',
    category: 'faceless',
    author: 'Minimalist',
    isPremium: false,
  },
  {
    id: 'abstract-gradient-flow',
    title: 'Soft Gradient Flow',
    src: 'https://videos.pexels.com/video-files/3191574/3191574-uhd_3840_2160_25fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/3191574/pexels-photo-3191574.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '05:00',
    size: '70 MB',
    category: 'aesthetic',
    author: 'Dreamscape',
    isPremium: false,
  },
  {
    id: 'cozy-fireplace-winter',
    title: 'Cozy Winter Fireplace',
    src: 'https://videos.pexels.com/video-files/5537799/5537799-hd_1080_1920_25fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/5537799/pexels-photo-5537799.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '12:00',
    size: '165 MB',
    category: 'faceless',
    author: 'HomeCozy',
    isPremium: true,
  },
  {
    id: 'morning-coffee-pour',
    title: 'Aesthetic Morning Coffee',
    src: 'https://videos.pexels.com/video-files/8063953/8063953-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/8063953/pexels-photo-8063953.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '04:00',
    size: '55 MB',
    category: 'aesthetic',
    author: 'DailyVlog',
    isPremium: false,
  },
  {
    id: 'train-ride-sunset',
    title: 'Sunset Train Ride POV',
    src: 'https://videos.pexels.com/video-files/14402560/14402560-uhd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/14402560/pexels-photo-14402560.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '08:30',
    size: '115 MB',
    category: 'faceless',
    author: 'Traveler',
    isPremium: false,
  },

  // --- NATURE / CINEMATIC (25) ---
  {
    id: 'forest-drone-shot',
    title: 'Cinematic Pine Forest',
    src: 'https://videos.pexels.com/video-files/15286/pexels-video-15286.mp4',
    thumbnail: 'https://images.pexels.com/photos/15286/pexels-photo-15286.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '07:00',
    size: '105 MB',
    category: 'nature',
    author: 'DronePilot',
    isPremium: false,
  },
  {
    id: 'ocean-waves-aerial',
    title: 'Deep Blue Ocean Waves',
    src: 'https://videos.pexels.com/video-files/2025634/2025634-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/2025634/pexels-photo-2025634.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '09:00',
    size: '135 MB',
    category: 'nature',
    author: 'Oceanic',
    isPremium: false,
  },
  {
    id: 'mountain-peaks-snow',
    title: 'Snowy Mountain Peaks',
    src: 'https://videos.pexels.com/video-files/14402560/14402560-uhd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/14402560/pexels-photo-14402560.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '11:00',
    size: '160 MB',
    category: 'nature',
    author: 'PeakViews',
    isPremium: true,
  },
  {
    id: 'starry-night-timelapse',
    title: 'Milky Way Timelapse',
    src: 'https://videos.pexels.com/video-files/3191574/3191574-uhd_3840_2160_25fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/3191574/pexels-photo-3191574.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '15:00',
    size: '230 MB',
    category: 'nature',
    author: 'Stargazer',
    isPremium: true,
  },
  {
    id: 'desert-sand-dunes',
    title: 'Golden Desert Dunes',
    src: 'https://videos.pexels.com/video-files/2025634/2025634-hd_1080_1920_30fps.mp4',
    thumbnail: 'https://images.pexels.com/photos/2025634/pexels-photo-2025634.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    duration: '06:00',
    size: '90 MB',
    category: 'nature',
    author: 'Sahara',
    isPremium: false,
  },
];

export const VOICE_OPTIONS: VoiceOption[] = [
  { id: 'william', name: 'William (OpenAI)', gender: 'male', age: 'middle-aged', language: 'english' },
  { id: 'adam', name: 'Adam (OpenAI)', gender: 'male', age: 'middle-aged', language: 'multilingual' },
  { id: 'dan-dan', name: 'Dan Dan (OpenAI)', gender: 'male', age: 'middle-aged', language: 'multilingual' },
  { id: 'natasha', name: 'Natasha (OpenAI)', gender: 'female', age: 'young', language: 'multilingual' },
  { id: 'amir-1', name: 'Amir #1 (OpenAI)', gender: 'male', age: 'young', language: 'multilingual' },
  { id: 'amir-2', name: 'Amir #2 (OpenAI)', gender: 'male', age: 'young', language: 'multilingual' },
  { id: 'sponge-bob', name: 'Sponge Bob (OpenAI)', gender: 'male', age: 'young', language: 'multilingual' },
  // ElevenLabs
  { id: 'rachel', name: 'Rachel (11Labs)', gender: 'female', age: 'young', language: 'english' },
  { id: 'domi', name: 'Domi (11Labs)', gender: 'female', age: 'young', language: 'english' },
  { id: 'bella', name: 'Bella (11Labs)', gender: 'female', age: 'young', language: 'english' },
  { id: 'antoni', name: 'Antoni (11Labs)', gender: 'male', age: 'young', language: 'english' },
  { id: 'elli', name: 'Elli (11Labs)', gender: 'female', age: 'young', language: 'english' },
  { id: 'josh', name: 'Josh (11Labs)', gender: 'male', age: 'middle-aged', language: 'english' },
  { id: 'arnold', name: 'Arnold (11Labs)', gender: 'male', age: 'middle-aged', language: 'english' },
  { id: 'adam-11', name: 'Adam (11Labs)', gender: 'male', age: 'middle-aged', language: 'english' },
  { id: 'sam', name: 'Sam (11Labs)', gender: 'male', age: 'young', language: 'english' },
];

export const MUSIC_OPTIONS: MusicOption[] = [
  { id: 'none', name: 'No background music', duration: '' },
  { id: 'green-to-blue', name: 'Green to Blue', duration: '3m 8s', src: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3' },
  { id: 'wii-shop', name: 'Wii Shop Trap Theme', duration: '1m 0s', src: 'https://samplelib.com/lib/preview/mp3/sample-6s.mp3' },
  { id: 'milk-cassete', name: 'Milk Cassete', duration: '5m 8s', src: 'https://samplelib.com/lib/preview/mp3/sample-9s.mp3' },
  { id: 'bladerunner', name: 'Bladerunner', duration: '3m 48s', src: 'https://samplelib.com/lib/preview/mp3/sample-12s.mp3' },
  { id: '3am-walk', name: '3am Walk', duration: '1m 0s', src: 'https://samplelib.com/lib/preview/mp3/sample-15s.mp3' },
  { id: 'fluffing-duck', name: 'Fluffing Duck', duration: '1m 7s', src: 'https://samplelib.com/lib/preview/mp3/sample-6s.mp3' },
  { id: 'temporary', name: 'I was only temporary', duration: '1m 0s', src: 'https://samplelib.com/lib/preview/mp3/sample-9s.mp3' },
];

export const REDDIT_VOICE_TO_TTS_VOICE = {
  william: 'onyx',
  adam: 'echo',
  'dan-dan': 'alloy',
  natasha: 'nova',
  'amir-1': 'shimmer',
  'amir-2': 'fable',
  'sponge-bob': 'alloy',
  emma: 'nova',
  james: 'onyx',
  sophia: 'shimmer',
  // ElevenLabs Mappings
  rachel: '21m00Tcm4TlvDq8ikWAM',
  domi: 'AZnzlk1XvdvUeBnXmlld',
  bella: 'EXAVITQu4vr4xnSDxMaL',
  antoni: 'ErXwobaYiN019PkySvjV',
  elli: 'MF3mGyEYCl7XYWbV9V6O',
  josh: 'TxGEqnHWrfWFTfGW9XjX',
  arnold: 'VR6AewLTigWg4xSOukaG',
  'adam-11': 'pNInz6obpgDQGcFmaJgB',
  sam: 'yoZ06aMxZJJ28mfd3POQ',
} as const;

export const SUBTITLE_STYLES: SubtitleStyle[] = [
  {
    id: 'crayo-modern',
    name: 'Crayo Modern',
    fontFamily: 'var(--type-family-display)',
    fontSize: 32,
    color: '#ffffff',
    backgroundColor: 'transparent',
    position: 'center',
    animation: 'pop',
  },
  {
    id: 'operator-white',
    name: 'Operator White',
    fontFamily: 'var(--type-family-display)',
    fontSize: 26,
    color: 'var(--color-text-primary)',
    backgroundColor: 'color-mix(in srgb, var(--color-background-primary) 55%, transparent)',
    position: 'bottom',
    animation: 'none',
  },
  {
    id: 'operator-accent',
    name: 'Operator Accent',
    fontFamily: 'var(--type-family-display)',
    fontSize: 30,
    color: 'var(--color-brand-primary)',
    backgroundColor: 'color-mix(in srgb, var(--color-background-primary) 40%, transparent)',
    position: 'center',
    animation: 'word-highlight',
  },
  {
    id: 'caption-slab',
    name: 'Caption Slab',
    fontFamily: 'var(--type-family-display)',
    fontSize: 24,
    color: 'var(--color-text-primary)',
    backgroundColor: 'color-mix(in srgb, var(--color-background-secondary) 92%, transparent)',
    position: 'bottom',
    animation: 'fade',
  },
  {
    id: 'caption-ghost',
    name: 'Caption Ghost',
    fontFamily: 'var(--type-family-display)',
    fontSize: 22,
    color: 'color-mix(in srgb, var(--color-text-primary) 82%, transparent)',
    backgroundColor: 'transparent',
    position: 'bottom',
    animation: 'pop',
  },
  {
    id: 'neon-inline',
    name: 'Neon Inline',
    fontFamily: 'var(--type-family-display)',
    fontSize: 28,
    color: 'var(--color-brand-secondary)',
    backgroundColor: 'transparent',
    position: 'center',
    animation: 'word-highlight',
  },
  {
    id: 'amber-punch',
    name: 'Amber Punch',
    fontFamily: 'var(--type-family-display)',
    fontSize: 30,
    color: 'var(--color-brand-accent)',
    backgroundColor: 'color-mix(in srgb, var(--color-background-primary) 35%, transparent)',
    position: 'center',
    animation: 'pop',
  },
  {
    id: 'pink-signal',
    name: 'Pink Signal',
    fontFamily: 'var(--type-family-display)',
    fontSize: 28,
    color: 'var(--color-brand-secondary)',
    backgroundColor: 'transparent',
    position: 'center',
    animation: 'fade',
  },
  {
    id: 'inkline',
    name: 'Inkline',
    fontFamily: 'var(--type-family-display)',
    fontSize: 24,
    color: 'color-mix(in srgb, var(--color-text-primary) 88%, transparent)',
    backgroundColor: 'color-mix(in srgb, var(--color-background-primary) 62%, transparent)',
    position: 'bottom',
    animation: 'none',
  },
  {
    id: 'subtle-outline',
    name: 'Subtle Outline',
    fontFamily: 'var(--type-family-display)',
    fontSize: 26,
    color: 'var(--color-text-primary)',
    backgroundColor: 'color-mix(in srgb, var(--color-background-secondary) 70%, transparent)',
    position: 'bottom',
    animation: 'fade',
  },
  {
    id: 'center-brief',
    name: 'Center Brief',
    fontFamily: 'var(--type-family-display)',
    fontSize: 26,
    color: 'var(--color-text-primary)',
    backgroundColor: 'transparent',
    position: 'center',
    animation: 'none',
  },
  {
    id: 'bottom-tight',
    name: 'Bottom Tight',
    fontFamily: 'var(--type-family-display)',
    fontSize: 22,
    color: 'var(--color-text-primary)',
    backgroundColor: 'color-mix(in srgb, var(--color-background-primary) 50%, transparent)',
    position: 'bottom',
    animation: 'none',
  },
  {
    id: 'top-banner',
    name: 'Top Banner',
    fontFamily: 'var(--type-family-display)',
    fontSize: 22,
    color: 'var(--color-text-primary)',
    backgroundColor: 'color-mix(in srgb, var(--color-background-secondary) 92%, transparent)',
    position: 'top',
    animation: 'fade',
  },
  {
    id: 'kinetic-word',
    name: 'Kinetic Word',
    fontFamily: 'var(--type-family-display)',
    fontSize: 34,
    color: 'var(--color-brand-primary)',
    backgroundColor: 'transparent',
    position: 'center',
    animation: 'word-highlight',
  },
  {
    id: 'mono-operator',
    name: 'Mono Operator',
    fontFamily: 'var(--type-family-mono)',
    fontSize: 22,
    color: 'color-mix(in srgb, var(--color-text-primary) 86%, transparent)',
    backgroundColor: 'color-mix(in srgb, var(--color-background-secondary) 86%, transparent)',
    position: 'bottom',
    animation: 'none',
  },
  {
    id: 'studio-card',
    name: 'Studio Card',
    fontFamily: 'var(--type-family-display)',
    fontSize: 24,
    color: 'var(--color-text-primary)',
    backgroundColor: 'color-mix(in srgb, var(--color-background-surface) 90%, transparent)',
    position: 'bottom',
    animation: 'pop',
  },
  {
    id: 'signal-strip',
    name: 'Signal Strip',
    fontFamily: 'var(--type-family-display)',
    fontSize: 24,
    color: 'var(--color-text-primary)',
    backgroundColor: 'color-mix(in srgb, var(--color-brand-primary) 12%, transparent)',
    position: 'bottom',
    animation: 'fade',
  },
];

export const ANIMATION_OPTIONS = [
  { id: 'none', labelKey: 'redditVideo.style.animNone' },
  { id: 'fade', labelKey: 'redditVideo.style.animFade' },
  { id: 'pop', labelKey: 'redditVideo.style.animPop' },
  { id: 'word-highlight', labelKey: 'redditVideo.style.animHighlight' },
] as const;

export const DEFAULT_REDDIT_INTRO = {
  username: 'Username',
  avatarUrl: '/reddit.png',
  isVerified: true,
  description: 'Video description goes here...',
  reactions: ['😀', '🤯', '😍', '🤔', '😢', '👏'],
  likes: 999,
  comments: 42,
};

export const INITIAL_STATE: RedditVideoState = {
  currentTab: 'script',
  scriptSource: 'prompt',
  redditUrl: '',
  storyTopic: '',
  tone: 'funny',
  language: 'en',
  lengthSeconds: 60,
  hook: '',
  cta: '',
  intro: DEFAULT_REDDIT_INTRO,
  scriptContent: '',
  subtitleDisplayMode: 'lines',
  showIntroCard: true,
  isDarkMode: false,
  selectedStyle: SUBTITLE_STYLES[0].id,
  selectedBackground: 'subway-surfers-1',
  uploadedBackgroundFile: null,
  uploadedBackgroundUrl: null,
  introVoice: 'william',
  scriptVoice: 'william',
  backgroundMusic: 'none',
  musicVolume: 0.3,
  voiceVolume: 1.0,
  subtitleStyle: SUBTITLE_STYLES[0],
  generatedIntroAudioUrl: null,
  generatedScriptAudioUrl: null,
  introDuration: 0,
  scriptDuration: 0,
  isGenerating: false,
  generationProgress: 0,
  isGenerated: false,
  validationError: null,
  generationError: null,
  isPlaying: false,
  currentTime: 0,
  duration: 0,
  isMuted: false,
};

export const SAMPLE_SCRIPT = '';

export { GENERATION } from '../../../constants/generation';
